/**
 * CityActivityDto - Data Transfer Object
 * 
 * Following powerview-admin patterns for DTO structure.
 * Generated by DomainGenerator.
 */

import { v4 as uuidv4 } from 'uuid';
import { 
  IsNotEmpty,
  IsEmail,
  ValidateNested,
  IsOptional
} from '@archbase/core';



export class CityActivityDto {
  @IsNotEmpty({
    message: "mentors:id cityactivity dever ser informado",
  })
  id: string;

  @IsOptional()
  code: string;

  @IsOptional()
  version: number;

  @IsOptional()
  createEntityDate: string;

  @IsOptional()
  updateEntityDate: string;

  @IsOptional()
  createdByUser: string;

  @IsOptional()
  lastModifiedByUser: string;

  // New record flag
  isNovoCityActivity: boolean;

  constructor(data: any) {
    this.id = data.id;
        this.code = data.code;
        this.version = data.version;
        this.createEntityDate = data.createEntityDate;
        this.updateEntityDate = data.updateEntityDate;
        this.createdByUser = data.createdByUser;
        this.lastModifiedByUser = data.lastModifiedByUser;
        
    this.isNovoCityActivity = data.isNovoCityActivity || false;
  }

  // Static factory method for new instances
  static newInstance = () => {
    return new CityActivityDto({
      id: uuidv4(),
      isNovoCityActivity: true
    });
  };

  // Audit helper methods
  isNewRecord(): boolean {
    return this.isNovoCityActivity || !this.id;
  }
}