/**
 * ProductStatus - Enum Definition
 * 
 * Generated enum following powerview-admin patterns
 * Generated by DomainGenerator.
 */

export enum ProductStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  DISCONTINUED = "DISCONTINUED"
}

// Enum utility functions
export const ProductStatusUtils = {
  // Get all enum values as array
  getValues: (): ProductStatus[] => {
    return Object.values(ProductStatus);
  },
  
  // Get enum value labels (for i18n)
  getLabel: (value: ProductStatus): string => {
    switch (value) {
      case ProductStatus.ACTIVE:
        return 'mentors:Active';
      case ProductStatus.INACTIVE:
        return 'mentors:Inactive';
      case ProductStatus.DISCONTINUED:
        return 'mentors:Discontinued';
      default:
        return value;
    }
  },
  
  // Check if value is valid
  isValid: (value: string): value is ProductStatus => {
    return Object.values(ProductStatus).includes(value as ProductStatus);
  },
  
  // Convert string to enum (with validation)
  fromString: (value: string): ProductStatus | undefined => {
    if (ProductStatusUtils.isValid(value)) {
      return value as ProductStatus;
    }
    return undefined;
  }
};