/**
 * Product Status Values - UI Rendering Configuration
 * 
 * Following powerview-admin patterns for enum rendering in UI components.
 * Generated by DomainGenerator.
 */

import { ArchbaseItemRenderType } from 'archbase-react';
import { ProductStatus } from './ProductStatus';

// Values for ProductStatus enum
export const ProductStatusValues: ArchbaseItemRenderType[] = [
  {
    value: ProductStatus.ACTIVE,
    label: 'mentors:Active',
    color: 'blue'
  },
  {
    value: ProductStatus.INACTIVE,
    label: 'mentors:Inactive',
    color: 'blue'
  },
  {
    value: ProductStatus.DISCONTINUED,
    label: 'mentors:Discontinued',
    color: 'blue'
  }
];


// Render function for ProductStatus
export const renderProductStatus = (value: ProductStatus): React.ReactNode => {
  const statusItem = ProductStatusValues.find(item => item.value === value);
  
  if (statusItem) {
    return (
      <Badge color={statusItem.color} variant="light">
        <Text size={'0.8rem'}>{t(statusItem.label)}</Text>
      </Badge>
    );
  }
  
  return value;
};

