/**
 * UserStatus - Enum Definition
 * 
 * Generated enum following powerview-admin patterns
 * Generated by DomainGenerator.
 */

export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING"
}

// Enum utility functions
export const UserStatusUtils = {
  // Get all enum values as array
  getValues: (): UserStatus[] => {
    return Object.values(UserStatus);
  },
  
  // Get enum value labels (for i18n)
  getLabel: (value: UserStatus): string => {
    switch (value) {
      case UserStatus.ACTIVE:
        return 'mentors:Active';
      case UserStatus.INACTIVE:
        return 'mentors:Inactive';
      case UserStatus.PENDING:
        return 'mentors:Pending';
      default:
        return value;
    }
  },
  
  // Check if value is valid
  isValid: (value: string): value is UserStatus => {
    return Object.values(UserStatus).includes(value as UserStatus);
  },
  
  // Convert string to enum (with validation)
  fromString: (value: string): UserStatus | undefined => {
    if (UserStatusUtils.isValid(value)) {
      return value as UserStatus;
    }
    return undefined;
  }
};