/**
 * UserDto - Data Transfer Object
 * 
 * Following powerview-admin patterns for DTO structure.
 * Generated by DomainGenerator.
 */

import { v4 as uuidv4 } from 'uuid';
import { 
  IsNotEmpty,
  IsEmail,
  ValidateNested,
  IsOptional
} from '@archbase/react';

import { UserStatus } from './UserStatus';


export class UserDto {
  @IsNotEmpty({
    message: "mentors:id user dever ser informado",
  })
  id: string;

  @IsOptional()
  code: string;

  @IsOptional()
  version: number;

  @IsOptional()
  createEntityDate: string;

  @IsOptional()
  updateEntityDate: string;

  @IsOptional()
  createdByUser: string;

  @IsOptional()
  lastModifiedByUser: string;

  @IsOptional()
  id: number;

  @IsOptional()
  name: string;

  @IsOptional()
  email: string;

  @IsOptional()
  status: string;

  // New record flag
  isNovoUser: boolean;

  constructor(data: any) {
    this.id = data.id;
        this.code = data.code;
        this.version = data.version;
        this.createEntityDate = data.createEntityDate;
        this.updateEntityDate = data.updateEntityDate;
        this.createdByUser = data.createdByUser;
        this.lastModifiedByUser = data.lastModifiedByUser;
        this.id = data.id;
        this.name = data.name;
        this.email = data.email;
        this.status = data.status;
        
    this.isNovoUser = data.isNovoUser || false;
  }

  // Static factory method for new instances
  static newInstance = () => {
    return new UserDto({
      id: uuidv4(),
      isNovoUser: true
    });
  };

  // Audit helper methods
  isNewRecord(): boolean {
    return this.isNovoUser || !this.id;
  }
}