/**
 * PlatformKPIDto - Data Transfer Object
 * 
 * Following powerview-admin patterns for DTO structure.
 * Generated by DomainGenerator.
 */

import { v4 as uuidv4 } from 'uuid';
import { 
  IsNotEmpty,
  IsEmail,
  ValidateNested,
  IsOptional
} from 'archbase-react';



export class PlatformKPIDto {
  @IsNotEmpty({
    message: "mentors:id platformkpi dever ser informado",
  })
  id: string;

  @IsOptional()
  code: string;

  @IsOptional()
  version: number;

  @IsOptional()
  createEntityDate: string;

  @IsOptional()
  updateEntityDate: string;

  @IsOptional()
  createdByUser: string;

  @IsOptional()
  lastModifiedByUser: string;

  @IsOptional()
  totalConnections: number;

  @IsOptional()
  activeStores: number;

  @IsOptional()
  totalRevenue: number;

  @IsOptional()
  conversionRate: number;

  @IsOptional()
  averageOrderValue: number;

  @IsOptional()
  dailyOrders: number;

  // New record flag
  isNovoPlatformKPI: boolean;

  constructor(data: any) {
    this.id = data.id;
        this.code = data.code;
        this.version = data.version;
        this.createEntityDate = data.createEntityDate;
        this.updateEntityDate = data.updateEntityDate;
        this.createdByUser = data.createdByUser;
        this.lastModifiedByUser = data.lastModifiedByUser;
        this.totalConnections = data.totalConnections;
        this.activeStores = data.activeStores;
        this.totalRevenue = data.totalRevenue;
        this.conversionRate = data.conversionRate;
        this.averageOrderValue = data.averageOrderValue;
        this.dailyOrders = data.dailyOrders;
        
    this.isNovoPlatformKPI = data.isNovoPlatformKPI || false;
  }

  // Static factory method for new instances
  static newInstance = () => {
    return new PlatformKPIDto({
      id: uuidv4(),
      isNovoPlatformKPI: true
    });
  };

  // Audit helper methods
  isNewRecord(): boolean {
    return this.isNovoPlatformKPI || !this.id;
  }
}