/**
 * TenantDto - Data Transfer Object
 * 
 * Following powerview-admin patterns for DTO structure.
 * Generated by DomainGenerator.
 */

import { v4 as uuidv4 } from 'uuid';
import { IsOptional } from 'archbase-react';


// Import nested DTOs (update paths as needed)
// import { return } from './return';

export class TenantDto {
  @IsOptional()
  id: string;

  @IsOptional()
  code: string;

  @IsOptional()
  version: number;

  @IsOptional()
  createEntityDate: string;

  @IsOptional()
  updateEntityDate: string;

  @IsOptional()
  createdByUser: string;

  @IsOptional()
  lastModifiedByUser: string;

  @IsOptional()
  name: string;

  @IsOptional()
  state: string;

  @IsOptional()
  country: string;

  @IsOptional()
  isActive: boolean;

  @IsOptional()
  boundaries: string;

  @IsOptional()
  timezone: string;

  @IsOptional()
  defaultCommissionRate: number;

  @IsOptional()
  defaultCashbackRate: number;

  // Removed invalid null property

  // New record flag
  isNovoTenant: boolean;

  constructor(data: any) {
    this.id = data.id;
        this.code = data.code;
        this.version = data.version;
        this.createEntityDate = data.createEntityDate;
        this.updateEntityDate = data.updateEntityDate;
        this.createdByUser = data.createdByUser;
        this.lastModifiedByUser = data.lastModifiedByUser;
        this.name = data.name;
        this.state = data.state;
        this.country = data.country;
        this.isActive = data.isActive;
        this.boundaries = data.boundaries;
        this.timezone = data.timezone;
        this.defaultCommissionRate = data.defaultCommissionRate;
        this.defaultCashbackRate = data.defaultCashbackRate;
        // Removed invalid null handling code
    
    this.isNovoTenant = data.isNovoTenant || false;
  }

  // Static factory method for new instances
  static newInstance = () => {
    return new TenantDto({
      id: uuidv4(),
      isNovoTenant: true
    });
  };

  // Audit helper methods
  isNewRecord(): boolean {
    return this.isNovoTenant || !this.id;
  }
}