/**
 * Conta Status Values - UI Rendering Configuration
 * 
 * Following powerview-admin patterns for enum rendering in UI components.
 * Generated by DomainGenerator.
 */

import { ArchbaseItemRenderType } from '@archbase/react';
import { StatusConta } from './StatusConta';

// Values for StatusConta enum
export const StatusContaValues: ArchbaseItemRenderType[] = [
  {
    value: StatusConta.ATIVA,
    label: 'mentors:Ativa',
    color: 'blue'
  },
  {
    value: StatusConta.INATIVA,
    label: 'mentors:Inativa',
    color: 'blue'
  },
  {
    value: StatusConta.BLOQUEADA,
    label: 'mentors:Bloqueada',
    color: 'blue'
  }
];


// Render function for StatusConta
export const renderStatusConta = (value: StatusConta): React.ReactNode => {
  const statusItem = StatusContaValues.find(item => item.value === value);
  
  if (statusItem) {
    return (
      <Badge color={statusItem.color} variant="light">
        <Text size={'0.8rem'}>{t(statusItem.label)}</Text>
      </Badge>
    );
  }
  
  return value;
};

