/**
 * Plataforma Status Values - UI Rendering Configuration
 * 
 * Following powerview-admin patterns for enum rendering in UI components.
 * Generated by DomainGenerator.
 */

import { ArchbaseItemRenderType } from '@archbase/react';
import { StatusPlataforma } from './StatusPlataforma';

// Values for StatusPlataforma enum
export const StatusPlataformaValues: ArchbaseItemRenderType[] = [
  {
    value: StatusPlataforma.ATIVO,
    label: 'mentors:Ativo',
    color: 'green'
  },
  {
    value: StatusPlataforma.INATIVO,
    label: 'mentors:Inativo',
    color: 'red'
  },
  {
    value: StatusPlataforma.MANUTENCAO,
    label: 'mentors:Manutencao',
    color: 'blue'
  }
];


// Render function for StatusPlataforma
export const renderStatusPlataforma = (value: StatusPlataforma): React.ReactNode => {
  const statusItem = StatusPlataformaValues.find(item => item.value === value);
  
  if (statusItem) {
    return (
      <Badge color={statusItem.color} variant="light">
        <Text size={'0.8rem'}>{t(statusItem.label)}</Text>
      </Badge>
    );
  }
  
  return value;
};

