/**
 * PlataformaDto - Data Transfer Object
 * 
 * Following powerview-admin patterns for DTO structure.
 * Generated by DomainGenerator.
 */

import { v4 as uuidv4 } from 'uuid';
import { 
  IsNotEmpty,
  IsEmail,
  ValidateNested,
  IsOptional
} from '@archbase/react';

import { StatusPlataforma } from './StatusPlataforma';

// Import nested DTOs (update paths as needed)
// import { StatusPlataforma } from './StatusPlataforma';

export class PlataformaDto {
  @IsNotEmpty({
    message: "mentors:id plataforma dever ser informado",
  })
  id: string;

  @IsOptional()
  code: string;

  @IsOptional()
  version: number;

  @IsOptional()
  createEntityDate: string;

  @IsOptional()
  updateEntityDate: string;

  @IsOptional()
  createdByUser: string;

  @IsOptional()
  lastModifiedByUser: string;

  @IsOptional()
  id: string;

  @IsNotEmpty({
    message: "mentors:nome plataforma dever ser informado",
  })
  nome: string;

  @IsNotEmpty({
    message: "mentors:descricao plataforma dever ser informado",
  })
  descricao: string;

  @IsOptional()
  statusPlataforma: StatusPlataforma;

  @IsOptional()
  isNovaPlataforma: boolean;

  // New record flag
  isNovoPlataforma: boolean;

  constructor(data: any) {
    this.id = data.id;
        this.code = data.code;
        this.version = data.version;
        this.createEntityDate = data.createEntityDate;
        this.updateEntityDate = data.updateEntityDate;
        this.createdByUser = data.createdByUser;
        this.lastModifiedByUser = data.lastModifiedByUser;
        this.id = data.id;
        this.nome = data.nome;
        this.descricao = data.descricao;
        // Handle nested object: statusPlataforma
    if (data.statusPlataforma) {
      this.statusPlataforma = new StatusPlataforma(data.statusPlataforma);
    }
    this.isNovaPlataforma = data.isNovaPlataforma;
        
    this.isNovoPlataforma = data.isNovoPlataforma || false;
  }

  // Static factory method for new instances
  static newInstance = () => {
    return new PlataformaDto({
      id: uuidv4(),
      isNovoPlataforma: true
    });
  };

  // Audit helper methods
  isNewRecord(): boolean {
    return this.isNovoPlataforma || !this.id;
  }
}