/**
 * Produto Status Values - UI Rendering Configuration
 * 
 * Following powerview-admin patterns for enum rendering in UI components.
 * Generated by DomainGenerator.
 */

import { ArchbaseItemRenderType } from '@archbase/react';
import { StatusProduto } from './StatusProduto';

// Values for StatusProduto enum
export const StatusProdutoValues: ArchbaseItemRenderType[] = [
  {
    value: StatusProduto.ATIVO,
    label: 'mentors:Ativo',
    color: 'green'
  },
  {
    value: StatusProduto.INATIVO,
    label: 'mentors:Inativo',
    color: 'red'
  },
  {
    value: StatusProduto.DESCONTINUADO,
    label: 'mentors:Descontinuado',
    color: 'blue'
  },
  {
    value: StatusProduto.EM_PROMOCAO,
    label: 'mentors:Em_promocao',
    color: 'blue'
  }
];


// Render function for StatusProduto
export const renderStatusProduto = (value: StatusProduto): React.ReactNode => {
  const statusItem = StatusProdutoValues.find(item => item.value === value);
  
  if (statusItem) {
    return (
      <Badge color={statusItem.color} variant="light">
        <Text size={'0.8rem'}>{t(statusItem.label)}</Text>
      </Badge>
    );
  }
  
  return value;
};

