/**
 * StatusConta - Enum Definition
 * 
 * Generated enum following powerview-admin patterns
 * Generated by DomainGenerator.
 */

export enum StatusConta {
  ATIVA = "ATIVA",
  INATIVA = "INATIVA",
  BLOQUEADA = "BLOQUEADA"
}

// Enum utility functions
export const StatusContaUtils = {
  // Get all enum values as array
  getValues: (): StatusConta[] => {
    return Object.values(StatusConta);
  },
  
  // Get enum value labels (for i18n)
  getLabel: (value: StatusConta): string => {
    switch (value) {
      case StatusConta.ATIVA:
        return 'mentors:Ativa';
      case StatusConta.INATIVA:
        return 'mentors:Inativa';
      case StatusConta.BLOQUEADA:
        return 'mentors:Bloqueada';
      default:
        return value;
    }
  },
  
  // Check if value is valid
  isValid: (value: string): value is StatusConta => {
    return Object.values(StatusConta).includes(value as StatusConta);
  },
  
  // Convert string to enum (with validation)
  fromString: (value: string): StatusConta | undefined => {
    if (StatusContaUtils.isValid(value)) {
      return value as StatusConta;
    }
    return undefined;
  }
};