/**
 * StatusProduto - Enum Definition
 * 
 * Generated enum following powerview-admin patterns
 * Generated by DomainGenerator.
 */

export enum StatusProduto {
  ATIVO = "ATIVO",
  INATIVO = "INATIVO",
  DESCONTINUADO = "DESCONTINUADO",
  EM_PROMOCAO = "EM_PROMOCAO"
}

// Enum utility functions
export const StatusProdutoUtils = {
  // Get all enum values as array
  getValues: (): StatusProduto[] => {
    return Object.values(StatusProduto);
  },
  
  // Get enum value labels (for i18n)
  getLabel: (value: StatusProduto): string => {
    switch (value) {
      case StatusProduto.ATIVO:
        return 'mentors:Ativo';
      case StatusProduto.INATIVO:
        return 'mentors:Inativo';
      case StatusProduto.DESCONTINUADO:
        return 'mentors:Descontinuado';
      case StatusProduto.EM_PROMOCAO:
        return 'mentors:Em_promocao';
      default:
        return value;
    }
  },
  
  // Check if value is valid
  isValid: (value: string): value is StatusProduto => {
    return Object.values(StatusProduto).includes(value as StatusProduto);
  },
  
  // Convert string to enum (with validation)
  fromString: (value: string): StatusProduto | undefined => {
    if (StatusProdutoUtils.isValid(value)) {
      return value as StatusProduto;
    }
    return undefined;
  }
};