/**
 * StatusPlataforma - Enum Definition
 * 
 * Generated enum following powerview-admin patterns
 * Generated by DomainGenerator.
 */

export enum StatusPlataforma {
  ATIVO = "ATIVO",
  INATIVO = "INATIVO",
  MANUTENCAO = "MANUTENCAO"
}

// Enum utility functions
export const StatusPlataformaUtils = {
  // Get all enum values as array
  getValues: (): StatusPlataforma[] => {
    return Object.values(StatusPlataforma);
  },
  
  // Get enum value labels (for i18n)
  getLabel: (value: StatusPlataforma): string => {
    switch (value) {
      case StatusPlataforma.ATIVO:
        return 'mentors:Ativo';
      case StatusPlataforma.INATIVO:
        return 'mentors:Inativo';
      case StatusPlataforma.MANUTENCAO:
        return 'mentors:Manutencao';
      default:
        return value;
    }
  },
  
  // Check if value is valid
  isValid: (value: string): value is StatusPlataforma => {
    return Object.values(StatusPlataforma).includes(value as StatusPlataforma);
  },
  
  // Convert string to enum (with validation)
  fromString: (value: string): StatusPlataforma | undefined => {
    if (StatusPlataformaUtils.isValid(value)) {
      return value as StatusPlataforma;
    }
    return undefined;
  }
};