/**
 * StatusUser - Enum Definition
 * 
 * Generated enum following powerview-admin patterns
 * Generated by DomainGenerator.
 */

export enum StatusUser {
  ATIVO = "ATIVO",
  INATIVO = "INATIVO",
  BLOQUEADO = "BLOQUEADO"
}

// Enum utility functions
export const StatusUserUtils = {
  // Get all enum values as array
  getValues: (): StatusUser[] => {
    return Object.values(StatusUser);
  },
  
  // Get enum value labels (for i18n)
  getLabel: (value: StatusUser): string => {
    switch (value) {
      case StatusUser.ATIVO:
        return 'mentors:Ativo';
      case StatusUser.INATIVO:
        return 'mentors:Inativo';
      case StatusUser.BLOQUEADO:
        return 'mentors:Bloqueado';
      default:
        return value;
    }
  },
  
  // Check if value is valid
  isValid: (value: string): value is StatusUser => {
    return Object.values(StatusUser).includes(value as StatusUser);
  },
  
  // Convert string to enum (with validation)
  fromString: (value: string): StatusUser | undefined => {
    if (StatusUserUtils.isValid(value)) {
      return value as StatusUser;
    }
    return undefined;
  }
};