/**
 * User Status Values - UI Rendering Configuration
 * 
 * Following powerview-admin patterns for enum rendering in UI components.
 * Generated by DomainGenerator.
 */

import { ArchbaseItemRenderType } from '@archbase/react';
import { StatusUser } from './StatusUser';

// Values for StatusUser enum
export const StatusUserValues: ArchbaseItemRenderType[] = [
  {
    value: StatusUser.ATIVO,
    label: 'mentors:Ativo',
    color: 'green'
  },
  {
    value: StatusUser.INATIVO,
    label: 'mentors:Inativo',
    color: 'red'
  },
  {
    value: StatusUser.BLOQUEADO,
    label: 'mentors:Bloqueado',
    color: 'orange'
  }
];


// Render function for StatusUser
export const renderStatusUser = (value: StatusUser): React.ReactNode => {
  const statusItem = StatusUserValues.find(item => item.value === value);
  
  if (statusItem) {
    return (
      <Badge color={statusItem.color} variant="light">
        <Text size={'0.8rem'}>{t(statusItem.label)}</Text>
      </Badge>
    );
  }
  
  return value;
};

